INSERT INTO CATEGORIA(NOME) VALUES('LIVROS');
INSERT INTO CATEGORIA(NOME) VALUES('ELETRONICOS');
INSERT INTO CATEGORIA(NOME) VALUES('COMPUTADORES');


INSERT INTO Produto (nome, preco, data, descricao, img_url) VALUES ('The Lord of the Rings', 90.5, TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO Produto (nome, preco, data, descricao, img_url) VALUES ('Smart TV', 2190.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/2-big.jpg');
INSERT INTO Produto (nome, preco, data, descricao, img_url) VALUES ('Macbook Pro', 1250.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/3-big.jpg');
INSERT INTO Produto (nome, preco, data, descricao, img_url) VALUES ('PC Gamer', 1200.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/4-big.jpg');
INSERT INTO Produto (nome, preco, data, descricao, img_url) VALUES ('Rails for Dummies', 100.99, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/5-big.jpg');
INSERT INTO Produto (nome, preco, data, descricao, img_url) VALUES ('PC Gamer Ex', 1350.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/6-big.jpg');
INSERT INTO Produto (nome, preco, data, descricao, img_url) VALUES ('PC Gamer X', 1350.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/7-big.jpg');
INSERT INTO Produto (nome, preco, data, descricao, img_url) VALUES ('PC Gamer Alfa', 1850.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/8-big.jpg');
INSERT INTO Produto (nome, preco, data, descricao, img_url) VALUES ('PC Gamer Tera', 1950.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/9-big.jpg');
INSERT INTO Produto (nome, preco, data, descricao, img_url) VALUES ('PC Gamer Y', 1700.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/10-big.jpg');
INSERT INTO Produto (nome, preco, data, descricao, img_url) VALUES ('PC Gamer Nitro', 1450.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/11-big.jpg');
INSERT INTO Produto (nome, preco, data, descricao, img_url) VALUES ('PC Gamer Card', 1850.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/12-big.jpg');
INSERT INTO Produto (nome, preco, data, descricao, img_url) VALUES ('PC Gamer Plus', 1350.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/13-big.jpg');
INSERT INTO Produto (nome, preco, data, descricao, img_url) VALUES ('PC Gamer Hera', 2250.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/14-big.jpg');
INSERT INTO Produto (nome, preco, data, descricao, img_url) VALUES ('PC Gamer Weed', 2200.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/15-big.jpg');
INSERT INTO Produto (nome, preco, data, descricao, img_url) VALUES ('PC Gamer Max', 2340.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/16-big.jpg');
INSERT INTO Produto (nome, preco, data, descricao, img_url) VALUES ('PC Gamer Turbo', 1280.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/17-big.jpg');
INSERT INTO Produto (nome, preco, data, descricao, img_url) VALUES ('PC Gamer Hot', 1450.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/18-big.jpg');
INSERT INTO Produto (nome, preco, data, descricao, img_url) VALUES ('PC Gamer Ez', 1750.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/19-big.jpg');
INSERT INTO Produto (nome, preco, data, descricao, img_url) VALUES ('PC Gamer Tr', 1650.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/20-big.jpg');
INSERT INTO Produto (nome, preco, data, descricao, img_url) VALUES ('PC Gamer Tx', 1680.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/21-big.jpg');
INSERT INTO Produto (nome, preco, data, descricao, img_url) VALUES ('PC Gamer Er', 1850.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/22-big.jpg');
INSERT INTO Produto (nome, preco, data, descricao, img_url) VALUES ('PC Gamer Min', 2250.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/23-big.jpg');
INSERT INTO Produto (nome, preco, data, descricao, img_url) VALUES ('PC Gamer Boo', 2350.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/24-big.jpg');
INSERT INTO Produto (nome, preco, data, descricao, img_url) VALUES ('PC Gamer Foo', 4170.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/25-big.jpg');

INSERT INTO Produto_Categoria (produto_id, categoria_id) VALUES (1, 2);
INSERT INTO Produto_Categoria (produto_id, categoria_id) VALUES (2, 1);
INSERT INTO Produto_Categoria (produto_id, categoria_id) VALUES (2, 3);
INSERT INTO Produto_Categoria (produto_id, categoria_id) VALUES (3, 3);
INSERT INTO Produto_Categoria (produto_id, categoria_id) VALUES (4, 3);
INSERT INTO Produto_Categoria (produto_id, categoria_id) VALUES (5, 2);
INSERT INTO Produto_Categoria (produto_id, categoria_id) VALUES (6, 3);
INSERT INTO Produto_Categoria (produto_id, categoria_id) VALUES (7, 3);
INSERT INTO Produto_Categoria (produto_id, categoria_id) VALUES (8, 3);
INSERT INTO Produto_Categoria (produto_id, categoria_id) VALUES (9, 3);
INSERT INTO Produto_Categoria (produto_id, categoria_id) VALUES (10, 3);
INSERT INTO Produto_Categoria (produto_id, categoria_id) VALUES (11, 3);
INSERT INTO Produto_Categoria (produto_id, categoria_id) VALUES (12, 3);
INSERT INTO Produto_Categoria (produto_id, categoria_id) VALUES (13, 3);
INSERT INTO Produto_Categoria (produto_id, categoria_id) VALUES (14, 3);
INSERT INTO Produto_Categoria (produto_id, categoria_id) VALUES (15, 3);
INSERT INTO Produto_Categoria (produto_id, categoria_id) VALUES (16, 3);
INSERT INTO Produto_Categoria (produto_id, categoria_id) VALUES (17, 3);
INSERT INTO Produto_Categoria (produto_id, categoria_id) VALUES (18, 3);
INSERT INTO Produto_Categoria (produto_id, categoria_id) VALUES (19, 3);
INSERT INTO Produto_Categoria (produto_id, categoria_id) VALUES (20, 3);
INSERT INTO Produto_Categoria (produto_id, categoria_id) VALUES (21, 3);
INSERT INTO Produto_Categoria (produto_id, categoria_id) VALUES (22, 3);
INSERT INTO Produto_Categoria (produto_id, categoria_id) VALUES (23, 3);
INSERT INTO Produto_Categoria (produto_id, categoria_id) VALUES (24, 3);
INSERT INTO Produto_Categoria (produto_id, categoria_id) VALUES (25, 3);

INSERT INTO Client (NAME, CPF, INCOME, BIRTH_DATE, CHILDREN) VALUES ('ISABEL DE SOUSA','97401345056',10,TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z',0)
INSERT INTO Client (NAME, CPF, INCOME, BIRTH_DATE, CHILDREN) VALUES ('JESSICA ANTUNES','37679064067',10,TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z',0)
INSERT INTO Client (NAME, CPF, INCOME, BIRTH_DATE, CHILDREN) VALUES ('LUCIA COSTA','45444152096',10,TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z',0)
INSERT INTO Client (NAME, CPF, INCOME, BIRTH_DATE, CHILDREN) VALUES ('LUIZ HENRIQUE','52711855082',10,TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z',0)
INSERT INTO Client (NAME, CPF, INCOME, BIRTH_DATE, CHILDREN) VALUES ('MARCELO CASTRO','13647910058',10,TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z',0)
INSERT INTO Client (NAME, CPF, INCOME, BIRTH_DATE, CHILDREN) VALUES ('JOSE SOUZA','60831283076',10,TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z',0)
INSERT INTO Client (NAME, CPF, INCOME, BIRTH_DATE, CHILDREN) VALUES ('JOSELIA SOUZA','16445256074',10,TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z',0)
INSERT INTO Client (NAME, CPF, INCOME, BIRTH_DATE, CHILDREN) VALUES ('ADAN SOARES','84824411084',10,TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z',0)
INSERT INTO Client (NAME, CPF, INCOME, BIRTH_DATE, CHILDREN) VALUES ('BRUNO CASTRO','62028992042',10,TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z',0)
INSERT INTO Client (NAME, CPF, INCOME, BIRTH_DATE, CHILDREN) VALUES ('CARLOS CAVALCANTE','40257782036',10,TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z',0)
INSERT INTO Client (NAME, CPF, INCOME, BIRTH_DATE, CHILDREN) VALUES ('CLETO ALENCAR','96097312016',10,TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z',0)
INSERT INTO Client (NAME, CPF, INCOME, BIRTH_DATE, CHILDREN) VALUES ('ESTELLA SILVA','67147013069',10,TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z',0)
INSERT INTO Client (NAME, CPF, INCOME, BIRTH_DATE, CHILDREN) VALUES ('FABIANA FERREIRA','92952620008',10,TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z',0)
INSERT INTO Client (NAME, CPF, INCOME, BIRTH_DATE, CHILDREN) VALUES ('FRANCISCA DA SILVA','85489451092',10,TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z',0)
INSERT INTO Client (NAME, CPF, INCOME, BIRTH_DATE, CHILDREN) VALUES ('GABRIEL SILVA','81009478052',10,TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z',0)
INSERT INTO Client (NAME, CPF, INCOME, BIRTH_DATE, CHILDREN) VALUES ('PAULO ALBERTO','25192602033',10,TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z',0)
INSERT INTO Client (NAME, CPF, INCOME, BIRTH_DATE, CHILDREN) VALUES ('OSIAS OLIVEIRA','30456913076',10,TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z',0)
INSERT INTO Client (NAME, CPF, INCOME, BIRTH_DATE, CHILDREN) VALUES ('NELSON NEDD','52422322000',10,TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z',0)
INSERT INTO Client (NAME, CPF, INCOME, BIRTH_DATE, CHILDREN) VALUES ('RAFAEL COSTA','41464866023',10,TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z',0)
INSERT INTO Client (NAME, CPF, INCOME, BIRTH_DATE, CHILDREN) VALUES ('WELLINGTON SANTOS','11198316012',10,TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z',0)
